<div class="span12 content">
	<h3>Password Sent</h3>
	<p>
	<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
		
		Your new password has now been sent to your email address. Please click 
		<a href="<?php
			echo $this->url(
				array(
					'module' => 'App',
					'controller' => 'Employee',
					'action' => 'index'
				),
				'module_partial_path',
				true);
			?>">here</a> 
		to return to the employee summary.
		
	<?php else: ?>
	
		Your new password has now been sent to your email address. Please click 
		<a href="<?php
			echo $this->url(
				array(
					'module' => 'App',
					'controller' => 'Login',
					'action' => 'index'
				),
				'module_partial_path',
				true);
			?>">here</a> 
		to login.
		
	<?php endif; ?>
	</p>
</div>