<div class="span3">
	<?php
		//$options['ulClass'] = 'nav nav-tabs nav-stacked';
		//$navContainer = Zend_Registry::get('app_sub_nav');
		//echo $this->getHelper('Navigation')->menu()->renderMenu($navContainer, $options);
	?>
</div>

<div class="span9 content">
	<h3>Password Recovery</h3>
	<p>Step 1 of 3</p>
	
	<?php
		$errorMessages = $this->form->getErrorMessages();
		if($errorMessages != null) {
			$isFirst = true;
			foreach($errorMessages as $currentMessage) {
				if($isFirst) {
					$isFirst = false;
					echo $currentMessage;
				}
				else {
					echo '<br>' . $errorMessage;
				}
			}
		}
	?>	

	<form id="<?php echo $this->form->getName(); ?>"
		name="<?php echo $this->form->getName(); ?>"
		method="<?php echo $this->form->getMethod(); ?>"
		action="<?php echo $this->form->getAction(); ?>"
		class="form-horizontal">
	
		<p>Please enter the email address you use to log into the system:</p>
		<div class="control-group">
			<label class="control-label" for="<?php echo $this->form->email->getName(); ?>">Email:</label>
			<div class="controls">
				<?php echo $this->form->email; ?>
			</div>
		</div>
		
		<hr>
		<p>Please type the charaters below into the text box:</p>
		<div class="control-group">
			<div class="controls">
				<?php echo $this->form->captcha; ?>
			</div>
		</div>
		
		<div class="control-group">
			<div class="controls">
				<?php echo $this->form->next; ?>
			</div>
		</div>
	</form>
	
</div>