<div class="span3">
	<?php
		if(Zend_Registry::isRegistered('app_sub_nav')) {
			$options['ulClass'] = 'nav nav-tabs nav-stacked';
			$navContainer = Zend_Registry::get('app_sub_nav');
			echo $this->getHelper('Navigation')->menu()->renderMenu($navContainer, $options);
		}
	?>
</div>

<div class="span9 content">
	<h3>TOIL History</h3>
	
	<div class="well">
    	You do not currently have any TOIL history recorded for this employee. Please use the links on the left of the page
    	to record TOIL accrued and used by this employee.
	</div>
</div>