<div class="span3">
	<?php
		$options['ulClass'] = 'nav nav-tabs nav-stacked';
		$navContainer = Zend_Registry::get('app_sub_nav');
		echo $this->getHelper('Navigation')->menu()->renderMenu($navContainer, $options);
	?>
</div>

<style type="text/css">
	.toil_owed {
		color: #B40404;
	}
	
	.toil_remaining {
		color: green;
	}
</style>

<div class="span9 content">
	<h3>Toil History</h3>
	
	<div class="well display stats">
    	<div class="row-fluid">
        	<div class="span6">
        	
            	<form id="<?php echo $this->form->getName(); ?>"
					name="<?php echo $this->form->getName(); ?>"
					action="<?php echo $this->form->getAction(); ?>"
					method="<?php echo $this->form->getMethod(); ?>"
					class="form-inline">
					
                	<div class="wiki-search">
                		<?php echo $this->form->employeeid; ?>
                		<?php echo $this->form->retrieve; ?>
                    </div>
                </form>
            </div>
            
            <div class="span6">
            	<?php if($this->isEmployeeSelected): ?>
            	
            		<?php
            			if($this->isOwed) {
							$balanceClass = 'class="toil_owed"';
							$balanceText = 'owed';
						} 
						else {
							$balanceClass = 'class="toil_remaining"';
							$balanceText = 'remaining';
						}
            		?>
	            	<h2 <?php echo $balanceClass; ?>>
	            		<?php echo $this->hours; ?>
	            	</h2>
	                <small>hours </small>
	                <h2 <?php echo $balanceClass; ?>>
	                	<?php echo $this->minutes; ?>
	                </h2>
	                <small>
	                	minutes <?php echo $balanceText; ?>
	                </small>
	                
                <?php endif; ?>
            </div>
        </div>
    </div>
    
    <?php if($this->isEmployeeSelected): ?>
    
	    <?php if(!$this->isToilHistoryAvailable): ?>
	    
			<div class="well">
		    	<strong><?php echo $this->employee->getName(); ?></strong> does not currently have any TOIL history.
		    	Please use the links on the left of the page to record TOIL accrued and used by this employee.
			</div>
			
		<?php else: ?>   
		          
			<table class="table table-bordered table-striped">
		    	<thead>
		        	<tr>
		            	<th>Date</th>
		                <th>Duration</th>
		                <th>Type</th>
		                <th>Edit</th>
		                <th>Delete</th>
		            </tr>
		        </thead>
		        <tbody>
		        	<?php foreach($this->toilList as $currentToil): ?>	
		        	<tr>
		            	<td><?php echo $currentToil->getDate() ?></td>
		            	<td><?php echo $currentToil->getDuration() ?></td>
		            	<td>
		            		<?php 
		            		if($currentToil->getToilAction() == Application_Model_Toil::ACCRUETOIL) {
								echo 'Accrued ';
							}
							else {
								echo 'Used ';
							}
							?>
		            	</td>
		            	
		            	<td>
		            		<a href="<?php 
		            			$toilPutLink = '/App/Toil/put/id/' . $currentToil->getId();
		            			$toilPutLink .= '/employeeid/' . $currentToil->getEmployeeId();
		            			echo $toilPutLink; 
		            			?>">Edit</a>
		            	</td>
		            	<td>
		            		<a href="<?php 
		            			$toilDeleteLink = '/App/Toil/delete/id/' . $currentToil->getId();
		            			$toilDeleteLink .= '/employeeid/' . $currentToil->getEmployeeId();
		            			echo $toilDeleteLink; 
		            			?>">Delete</a>
		            	</td>
		            </tr>
		            <?php endforeach; ?>
		        </tbody>
		    </table>
		    
	    <?php endif; ?>
	    
    <?php endif; ?>
</div>