<div class="span3">
	<?php
		if(Zend_Registry::isRegistered('app_sub_nav')) {
			$options['ulClass'] = 'nav nav-tabs nav-stacked';
			$navContainer = Zend_Registry::get('app_sub_nav');
			echo $this->getHelper('Navigation')->menu()->renderMenu($navContainer, $options);
		}
	?>
</div>

<div class="span9 content">
	<h3>Toil History</h3>
	
	<div class="well">
		You must add employees to your team before you can manage the TOIL history associated with them.
		Please visit <strong>Team Summary</strong> link at the top of the page 
		to add employees to your team.
	</div>
</div>