<div class="span3">
	<ul class="nav nav-tabs nav-stacked">
		<li class="sidebar_element">
			Content goes here content goes here content goes here.
		</li>
		<li class="sidebar_element">
			Content goes here content goes here content goes here.
		</li>
    </ul>
</div>

<div class="span9 content">
	<div class="banner">
    	<h2>Contact</h2>
    </div>
    
    <p>There are some good news for you today to find out.</p>
</div>