<h3>Terms and Conditions</h3>

<p>
Hello, welcome to the terms page. Oh yes, these fascinating terms are here to be scrutinised carefully by all 
customers, because that's what we all do, right? Alas, I'm going to have to ask you to agree to these terms 
before you can use the software, mostly to cover my ass against the more litigious elements of society. So, 
lets begin - we start with an easy one:
</p>

<p>
You agree not to sue me for anything relating to this software.
</p>

<p>
Next one. Ah yes, I'll do my best to provide great software and a great service, however, I'm fallible and so 
sometimes the software may break when something happens that I haven't programmed for. This should be rare 
because I have a massive brain, but I just want to put that out there. You agree not to go ape when this happens.
</p>

<p>
Ok, here's another: I'll make the software available for as long as I can support it, however, at some point I 
may no longer be able to support the service and have to close things down. I'll let you know well in advance, 
although I'm going to keep the definition 'well' loosely defined right now. Reckon on around a month. You agree 
to this, of course.
</p>

<p>
I'll provide a reasonable response time if you have a query. If I'm half-way through a burger or a speed-date, 
then the response time may stretch out somewhat Fortunately, time-off software isn't mission critical to any business, 
so you agree to wait patiently for my sage responses.
</p>

<p>
There's plenty of other terms I've haven't thought of, or have thought of but am unwilling to relate, largely 
because I'm bored now. So I'll make things easier, mostly for me, and say you agree to agree to any future 
changes to these terms, which I'll notify you of in advance of the change.
</p>

