<div class="span3">
	<?php
		//$options['ulClass'] = 'nav nav-tabs nav-stacked';
		//$navContainer = Zend_Registry::get('app_sub_nav');
		//echo $this->getHelper('Navigation')->menu()->renderMenu($navContainer, $options);
	?>
</div>

<div class="span9 content">
	<h3>One Step Registration</h3>

	<?php
		$errorMessages = $this->form->getErrorMessages();
		if($errorMessages != null) {
			$isFirst = true;
			foreach($errorMessages as $currentMessage) {
				if($isFirst) {
					$isFirst = false;
					echo $currentMessage;
				}
				else {
					echo '<br>' . $errorMessage;
				}
			}
		}
	?>
	
	<form id="<?php echo $this->form->getName(); ?>"
		name="<?php echo $this->form->getName(); ?>"
		method="<?php echo $this->form->getMethod(); ?>"
		action="<?php echo $this->form->getAction(); ?>"
		class="form-horizontal">
		
		<p>Your personal information:</p>
		<div class="control-group">
			<label class="control-label" for="<?php echo $this->form->name->getName(); ?>">Name:</label>
			<div class="controls">
				<?php echo $this->form->name; ?>
			</div>
		</div>
		
		<hr>
        <p>Please provide your email address. This will be used to login:</p>
		
		<div class="control-group">
			<label class="control-label" for="<?php echo $this->form->email->getName(); ?>">Email:</label>
			<div class="controls">
				<?php echo $this->form->email; ?>
			</div>
		</div>
		
		<div class="control-group">
			<label class="control-label" for="<?php echo $this->form->confirm_email->getName(); ?>">Confirm email:</label>
			<div class="controls">
				<?php echo $this->form->confirm_email; ?>
			</div>
		</div>
		
		<hr>
        <p>Please enter a secure password. Should be 6 characters or more in length.</p>
		
		<div class="control-group">
			<label class="control-label" for="<?php echo $this->form->password->getName(); ?>">Password:</label>
			<div class="controls">
				<?php echo $this->form->password; ?>
			</div>
		</div>
		
		<div class="control-group">
			<label class="control-label" for="<?php echo $this->form->confirm_password->getName(); ?>">Confirm password:</label>
			<div class="controls">
				<?php echo $this->form->confirm_password; ?>
			</div>
		</div>
		
		<hr>
        <p>
        Please select a question from the drop and provide an answer. This will be used to reset
        your password if you forget it.
        </p>
		
		<!-- 
		<div class="control-group">
			<label class="control-label" for="cant_be_bothered">Cant be bothered:</label>
			<div class="controls">
				<input id="cant_be_bothered" name="cant_be_bothered" type="checkbox">
			</div>
		</div>
		-->
		
		<div class="control-group">
			<label class="control-label" for="<?php echo $this->form->canned_questions->getName(); ?>">Security question 1:</label>
			<div class="controls">
				<?php echo $this->form->canned_questions; ?>
			</div>
		</div>
		
		<div class="control-group">
			<label class="control-label" for="<?php echo $this->form->canned_answer->getName(); ?>">Security answer 1:</label>
			<div class="controls">
				<?php echo $this->form->canned_answer; ?>
			</div>
		</div>
		
		<hr>
        <p>
        Please enter your own question and answer. This will be presented to you if you forget your password, so
        that the software can verify who you are. Question / answers are encrypted on the system, so feel free to
        make this question anything you want.
        </p>
		
		<!-- 
		<div class="control-group">
			<label class="control-label" for="dont_wanna">Dont wanna:</label>
			<div class="controls">
				<input id="dont_wanna" name="dont_wanna" type="checkbox">
			</div>
		</div>
		-->
		
		<div class="control-group">
			<label class="control-label" for="<?php echo $this->form->user_created_question->getName(); ?>">Security question 2:</label>
			<div class="controls">
				<?php echo $this->form->user_created_question; ?>
			</div>
		</div>
		
		<div class="control-group">
			<label class="control-label" for="<?php echo $this->form->user_created_answer->getName(); ?>">Security answer 2:</label>
			<div class="controls">
				<?php echo $this->form->user_created_answer; ?>
			</div>
		</div>
		
		<hr>
		<div class="control-group">
			<div class="controls">
				<label class="checkbox">
					<?php
						//Identify any error with the terms. Make a note of this and switch off
						//the error. We will display the error message underneath this label.
						$isErrored = false;
						if($this->form->terms->hasErrors()) {
							$isErrored = true;
						}
						echo $this->form->terms; 
					?>
					Please tick here to confirm that you will abide by the excessively verbose and largely
					inpenetrable
						<a target="_blank" href="<?php 
							echo $this->getHelper('Url')->url(array(
					    	'module' => 'default',
					        'controller' => 'Index',
					        'action' => 'terms'	
				    	),
				        'default',
				        true); ?>">terms of use</a>. Go ahead, check them out.
					
					<?php 
						//If there is an error with the terms, display it here.
						if($isErrored) {
							echo '<ul><li>You must agree to the terms before you can register</li></ul>';
						}
					?>
				</label>
			</div>
		</div>
		
		<hr>
		<p>
			Finally, please prove that you are not a bot by typing the letters you see in the image below.
		</p>
		<div class="control-group">
			<div class="controls">
				<?php echo $this->form->captcha; ?>
			</div>
		</div>
		
		<div class="control-group">
			<div class="controls">
				<?php echo $this->form->register; ?>
			</div>
		</div>
	</form>
</div>