<div id="view-content">
<form id="<?php echo $this->form->getName(); ?>"
	name="<?php echo $this->form->getName(); ?>"
	method="<?php echo $this->form->getMethod(); ?>"
	action="<?php echo $this->form->getAction(); ?>">
	
	<fieldset>
		<label for="<?php echo $this->form->current_password->getName(); ?>">Current password:</label>
		<?php echo $this->form->current_password; ?>
	</fieldset>
	
	<fieldset>
		<label for="<?php echo $this->form->new_password->getName(); ?>">New password:</label>
		<?php echo $this->form->new_password; ?>

		<label for="<?php echo $this->form->confirm_new_password->getName(); ?>">Confirm new password:</label>
		<?php echo $this->form->confirm_new_password; ?>
	</fieldset>
	
	<fieldset>
		<?php echo $this->form->apply; ?>
	</fieldset>
</form>
</div>