<div class="span3">
	<?php
		$options['ulClass'] = 'nav nav-tabs nav-stacked';
		$navContainer = Zend_Registry::get('app_sub_nav');
		echo $this->getHelper('Navigation')->menu()->renderMenu($navContainer, $options);
	?>
</div>

<div class="span9 content">
	<h3>Team Summary</h3>
	<table class="table table-bordered table-striped">
    	<thead>
        	<tr>
            	<th class="optional">Employee name</th>
                <th>TOIL Balance</th>
                <th class="optional">View TOIL</th>
                <th class="optional">Edit employee</th>
                <th>Delete employee</th>
            </tr>
        </thead>
        <tbody>
        	<?php foreach($this->employees as $currentEmployee): ?>	
        	<tr>
            	<td><?php echo $currentEmployee->getName(); ?></td>
            	<td>
            		<?php
            			$hours = $currentEmployee->getToilBalance()->getHours(); 
            			$minutes = $currentEmployee->getToilBalance()->getMinutes();
            			$isOwed = $currentEmployee->getToilBalance()->getIsOwed();
            			if(($hours == 0) && ($minutes == 0)) {
							$symbol = '';
						}
						else {
	            			if($isOwed) { 
								$symbol = '- ';
							}
							else {
								$symbol = '+ ';
							}
						}
            			echo $symbol . $hours . ' hrs ' . $minutes . ' mins';
            		?>
            	</td>
            	<td>
            		<a href="/App/Toil/index/employeeid/<?php echo $currentEmployee->getId(); ?>">View</a>
            	</td>
            	<td>
            		<a href="/App/Employee/put/id/<?php echo $currentEmployee->getId(); ?>">Edit</a>
            	</td>
            	<td>
            		<a href="/App/Employee/delete/id/<?php echo $currentEmployee->getId(); ?>">Delete</a>
            	</td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>